services:
  - type: web
    name: projek-cloud-1
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: "Projek Cloud 1"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
